// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgvK7JxQaGyJIg8yVIigbg8m2SekotV4',
    appId: '1:383874048481:web:af4793fee5b716cb5bb2a0',
    messagingSenderId: '383874048481',
    projectId: 'chat--app-fb5f9',
    authDomain: 'chat--app-fb5f9.firebaseapp.com',
    storageBucket: 'chat--app-fb5f9.appspot.com',
    measurementId: 'G-9XVX4LBJSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlPy2VZxPLzEMjUsPfaBnwa_Y1-XVvE8',
    appId: '1:383874048481:android:ff60374217f22bad5bb2a0',
    messagingSenderId: '383874048481',
    projectId: 'chat--app-fb5f9',
    storageBucket: 'chat--app-fb5f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nT3ki-at_OCH-8r5-kEk_G2iiwgTfdY',
    appId: '1:383874048481:ios:71340ec67b5a16cd5bb2a0',
    messagingSenderId: '383874048481',
    projectId: 'chat--app-fb5f9',
    storageBucket: 'chat--app-fb5f9.appspot.com',
    iosClientId: '383874048481-0dti1d78ienntjobmeck52sa45852gt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nT3ki-at_OCH-8r5-kEk_G2iiwgTfdY',
    appId: '1:383874048481:ios:71340ec67b5a16cd5bb2a0',
    messagingSenderId: '383874048481',
    projectId: 'chat--app-fb5f9',
    storageBucket: 'chat--app-fb5f9.appspot.com',
    iosClientId: '383874048481-0dti1d78ienntjobmeck52sa45852gt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
